from codecamp.ember import views
from django.conf.urls.defaults import patterns, url, include

urlpatterns = patterns('',
    url(r'^/tags/$', views.TagList.as_view()),
    url(r'^/ratings/$', views.RatingList.as_view()),
    url(r'^/speakers/$', views.SpeakerList.as_view()),
    url(r'^/personas/$', views.PersonaList.as_view()),
    url(r'^/companies/$', views.CompanyList.as_view()),
    url(r'^/sponsors/$', views.SponsorList.as_view()),
    url(r'^/associations/$', views.AssociationList.as_view()),
    url(r'^/sessions/$', views.SessionList.as_view()),
    url(r'^/tags/(?P<pk>\d+)/$', views.TagDetail.as_view()),
    url(r'^/ratings/(?P<pk>\d+)/$', views.RatingDetail.as_view()),
    url(r'^/users/(?P<pk>\d+)/$', views.UserDetail.as_view()),
    url(r'^/speakers/(?P<pk>\d+)/$', views.SpeakerDetail.as_view()),
    url(r'^/personas/(?P<pk>\d+)/$', views.PersonaDetail.as_view()),
    url(r'^/companies/(?P<pk>\d+)/$', views.CompanyDetail.as_view()),
    url(r'^/sponsors/(?P<pk>\d+)/$', views.SponsorDetail.as_view()),
    url(r'^/associations/(?P<pk>\d+)/$', views.AssociationDetail.as_view()),
    url(r'^/sessions/(?P<pk>\d+)/$', views.SessionDetail.as_view()),
    url(r'^/sessions/(?P<session_pk>\d+)/tags/$', views.TagBySessionList.as_view()),
    url(r'^/sessions/(?P<session_pk>\d+)/ratings/$', views.RatingBySessionList.as_view()),
    url(r'^/sessions/(?P<session_pk>\d+)/speakers/$', views.SpeakerBySessionList.as_view()),
    url(r'^/associations/(?P<association_pk>\d+)/speakers/$', views.SpeakerByAssociationList.as_view()),
    url(r'^/speakers/(?P<speaker_pk>\d+)/personas/$', views.PersonaBySpeakerList.as_view()),
    url(r'^/companies/(?P<company_pk>\d+)/sponsors/$', views.SponsorByCompanyList.as_view()),
)
